# Needleman Wunsch alignment

In [23]:
import numpy as np

In [ ]:
seq1 = "ATGCG"
seq2 = "ATCGC"

In [25]:
main_matrix = np.zeros((len(seq1)+1,len(seq2)+1))

In [27]:
main_matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
match_checker_matrix = np.zeros((len(seq1),len(seq2)))

In [29]:
match_checker_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
match = 1
mismatch = -1
gap_penality = -2

In [42]:
for i in range (len(seq1)):
    for j in range (len(seq2)):
        if (seq1[i] == seq2[j]):
            match_checker_matrix[i][j] = match
        else:
            match_checker_matrix[i][j] = mismatch

In [43]:
for i in range(len(seq1)+1):
    main_matrix[i][0] = i*gap_penality
    
for j in range(len(seq2)+1):
    main_matrix[0][j] = j * gap_penality

In [44]:
for i in range(1, len(seq1)+1):
    for j in range(1, len(seq2)+1):
        main_matrix[i][j] = max(main_matrix[i-1][j-1] + match_checker_matrix[i-1][j-1],
                               main_matrix[i-1][j] + gap_penality,
                               main_matrix[i][j-1] + gap_penality)

In [45]:
main_matrix

array([[  0.,  -2.,  -4.,  -6.,  -8., -10.],
       [ -2.,   1.,  -1.,  -3.,  -5.,  -7.],
       [ -4.,  -1.,   2.,   0.,  -2.,  -4.],
       [ -6.,  -3.,   0.,   1.,   1.,  -1.],
       [ -8.,  -5.,  -2.,   1.,   0.,   2.],
       [-10.,  -7.,  -4.,  -1.,   2.,   0.]])

In [51]:
aligned1 = ""
aligned2 = ""

ti = len(aligned1)-1
tj = len(aligned2)-1

while(ti > 0 and tj > 0):
    
    if(ti > 0 and tj > 0 and main_matrix[ti][tj] == main_matrix[ti-1][tj-1] + match_checker_matrix[ti-1][tj-1]):
        aligned1 = seq1[ti-1] + aligned1
        aligned2 = seq2[tj-1] + aligned2
        
        ti = ti-1
        tj = tj-1
    
    elif (ti > 0 and main_matrix[ti][tj] ==main_matrix[ti-1][tj] + gap_penality ):
        aligned1 = seq1[ti-1] + aligned1
        aligned2 = "-" + aligned2
        ti = ti-1

        
    else:
        aligned1 = "-" + aligned1
        aligned2 = seq2[tj-1] + aligned2
        
        tj = tj - 1

        
    
    

In [52]:
aligned1

''

In [1]:
def needleman_wunsch(seq1, seq2, gap_penalty, match_score, mismatch_score):
    # Initialize the score matrix
    rows = len(seq1) + 1
    cols = len(seq2) + 1
    score = [[0 for j in range(cols)] for i in range(rows)]

    # Initialize the first row and column of the score matrix
    for i in range(1, rows):
        score[i][0] = gap_penalty * i
    for j in range(1, cols):
        score[0][j] = gap_penalty * j

    # Fill in the rest of the score matrix
    for i in range(1, rows):
        for j in range(1, cols):
            # Calculate the score for a match or mismatch
            if seq1[i - 1] == seq2[j - 1]:
                match = score[i - 1][j - 1] + match_score
            else:
                match = score[i - 1][j - 1] + mismatch_score
            # Calculate the score for a gap in sequence 1
            gap1 = score[i - 1][j] + gap_penalty
            # Calculate the score for a gap in sequence 2
            gap2 = score[i][j - 1] + gap_penalty
            # Choose the maximum score
            score[i][j] = max(match, gap1, gap2)

    # Traceback to find the optimal alignment
    align1 = ''
    align2 = ''
    i = rows - 1
    j = cols - 1
    while i > 0 and j > 0:
        if score[i][j] == score[i - 1][j - 1] + (match_score if seq1[i - 1] == seq2[j - 1] else mismatch_score):
            align1 = seq1[i - 1] + align1
            align2 = seq2[j - 1] + align2
            i -= 1
            j -= 1
        elif score[i][j] == score[i - 1][j] + gap_penalty:
            align1 = seq1[i - 1] + align1
            align2 = '-' + align2
            i -= 1
        else:
            align1 = '-' + align1
            align2 = seq2[j - 1] + align2
            j -= 1

    # Add any remaining characters
    while i > 0:
        align1 = seq1[i - 1] + align1
        align2 = '-' + align2
        i -= 1
    while j > 0:
        align1 = '-' + align1
        align2 = seq2[j - 1] + align2
        j -= 1

    return align1, align2, score[-1][-1]




In [2]:
seq1 = "abcde"
seq2 = "cabccde"
print(needleman_wunsch(seq1,seq2,-1,2,-1))

('-ab-cde', 'cabccde', 8)
